language: python
dist: bionic
python:
 - 3.8
 - nightly

jobs:
  allow_failures:
  - python: nightly

install:
    - sudo apt-get -qq update
    - sudo apt-get -y install git
    - pip3 install flake8

script: .travis/flake8.sh
