language: python
dist: bionic
python: 3.8

jobs:
  allow_failures:
  - python: nightly
  include:
  - name: Python 3.8 x64
  - name: Python 3.8 Arm
    arch: arm64
  - name: Python Nightly x64
    python: nightly

before_install:
  - python --version
  - pip3 install -U pip
  - pip3 install -U flake8 pytest codecov requests

install: pip install ".[test]" .

script:
 - .travis/flake8.sh
 - pytest # run tests

after_success:
  - codecov
